/* Generated by tools/gen_maps.py - do not edit by hand. */
#include "game.h"

static const char *const rows_players_house[] = {
    "IIIIIIIIIII",
    "I_________I",
    "I_B__t____I",
    "I____r____I",
    "I____r____I",
    "I_________I",
    "I_K___C__pI",
    "I_________I",
    "IIIIIMIIIII",
};

static const char *const rows_maples_lab[] = {
    "IIIIIIIIIIIII",
    "I___K___K___I",
    "I___________I",
    "I__C_____C__I",
    "I___________I",
    "I_____rr____I",
    "I_____rr____I",
    "I___________I",
    "I___________I",
    "IIIIIIMIIIIII",
};

static const char *const rows_care_station[] = {
    "IIIIIIIIII",
    "I_______CI",
    "I________I",
    "INNNNN__pI",
    "I________I",
    "I_r______I",
    "I________I",
    "IIIMIIIIII",
};

static const char *const rows_verdan_town[] = {
    "TTTTTTTTTTTTTggTTTTTTTTTTTTT",
    "TggggggggggggggggggggggggggT",
    "TggggggggggggggggggggggggggT",
    "Tgg,g,,,,gggggggg,,,,,gggggT",
    "Tgggggggggggggggg(^^^^)ggggT",
    "Tgg(^^^)ggggggggg#OHOO#ggggT",
    "Tgg#ODO#gggggggggggggggggggT",
    "TggggPgggggggggggggPg(^^^^)T",
    "TggggPgggggggggggggPg#ODOO#T",
    "TggggPPPPPPPPPPPPPPPPPPPgggT",
    "TggggggggggggPPggggggggggggT",
    "TggggggggggggPPggggggggggggT",
    "TggggggggggggPPggggggggggggT",
    "Tggggggggg(^^^^^)ggggggggggT",
    "Tggggggggg#OODOO#ggggggggggT",
    "TggggggggggggPgggggggggggggT",
    "TggggggggggggPgSgggggggggggT",
    "TgsWWWWWWWsggggggggggggggggT",
    "TgsWWWWWWWsggggggggggggggggT",
    "TgsssssssssggggggggggggggggT",
    "TgggggggggggFFFFFFFggggggggT",
    "TgggggggggggF,,,,,FggggggggT",
    "TgggggggggggFFFFFFFggggggggT",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
};

static const char *const rows_route_1[] = {
    "TTTTTTTTTT..TTTTTTTT",
    "TgggggggggRRRggggggT",
    "TgggggggggRRRggggggT",
    "Tggg,,gggg,,gggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "TgggggggggPPgggggggT",
    "Tgggg\"\"gggPPggg\"\"ggT",
    "Tgggg\"\"gggPPggg\"\"ggT",
    "Tgggg\"\"gggPPggg\"\"ggT",
    "TgggggggggPPgggggggT",
    "TggRggggggPPggggggRT",
    "TgggggggggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPLLLLLLgT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPgggggggT",
    "TggggRggggPPgggggggT",
    "TgggggggggPPgggggggT",
    "Tgg\"\"\"\"gggPPgg\"\"\"ggT",
    "Tgg\"\"\"\"gggPPgg\"\"\"ggT",
    "Tgg\"\"\"\"gggPPgg\"\"\"ggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPggggSggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "Tgg\"\"\"\"gggPPgggggggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPgggggggT",
    "TTTTTTTTTT..TTTTTTTT",
};

static const char *const rows_verdan_mart[] = {
    "IIIIIIIIII",
    "I________I",
    "I__K__K__I",
    "INNNNN__pI",
    "I________I",
    "I_r______I",
    "I________I",
    "IIIMIIIIII",
};

static const char *const rows_route_2[] = {
    "TTTTTTTTTTTTTTTTTTTT",
    "TgggggggggPPggggggST",
    "TgggggggggPPgggggggT",
    "Tgggg,,gggPPgggggggT",
    "Tgggg,,gggPPgggggggT",
    "TgggggggggPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPgggsWWsT",
    "TgggggggggPPgggsWWsT",
    "TgggggggggPPggggssgT",
    "Tggggg\"\"\"gPPgggggggT",
    "Tggggg\"\"\"gPPgggggggT",
    "Tggggg\"\"\"gPPgggggggT",
    "TgggggggggPPLLLLLLgT",
    "TgggggggggPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "Tgg\"\"\"\"\"\"gPPgggggggT",
    "TgggggggggPPgggggggT",
    "TgggggggggPPggggggST",
    "TTTTTTTTTT..TTTTTTTT",
};

static const Warp warps_0[] = {
    {5, 8, 3, 5, 7},
};

static const Warp warps_1[] = {
    {6, 9, 3, 13, 15},
};

static const Warp warps_2[] = {
    {3, 7, 3, 19, 6},
};

static const Warp warps_3[] = {
    {13, 0, 4, 10, 32},
    {14, 0, 4, 11, 32},
    {5, 6, 0, 5, 8},
    {19, 5, 2, 3, 7},
    {13, 14, 1, 6, 9},
    {23, 8, 5, 3, 7},
};

static const Warp warps_4[] = {
    {10, 33, 3, 13, 1},
    {11, 33, 3, 14, 1},
    {10, 0, 6, 10, 24},
    {11, 0, 6, 11, 24},
};

static const Warp warps_5[] = {
    {3, 7, 3, 23, 9},
};

static const Warp warps_6[] = {
    {10, 25, 4, 10, 1},
    {11, 25, 4, 11, 1},
};

static const char *const dlg_kid_pond[] = {
    "There's a huge fish in here!",
    "It splashed me! Soaked!",
    NULL};
static const char *const dlg_assistant[] = {
    "PROF. MAPLE studies the wild",
    "creatures of our region.",
    "She's waiting for you - go",
    "talk to her!",
    NULL};
static const char *const dlg_hiker[] = {
    "Whoa there! A landslide has",
    "closed the road north.",
    "Come back once it's cleared!",
    NULL};
static const char *const dlg_villager[] = {
    "Tall grass hides creatures!",
    "Walk through it and you're",
    "bound to meet one!",
    NULL};
static const char *const dlg_liam_pre[] = {
    "Hey! You have creatures too?",
    "Let's see whose partner is",
    "stronger!",
    NULL};
static const char *const dlg_liam_post[] = {
    "Your partner is so strong!",
    "I need to train more!",
    NULL};
static const char *const dlg_maya_pre[] = {
    "PICNICKER MAYA: This is my",
    "favorite picnic spot!",
    "Let's battle for it!",
    NULL};
static const char *const dlg_maya_post[] = {
    "Fine, you can share the",
    "spot. Picnics are better",
    "with friends anyway!",
    NULL};
static const char *const dlg_denim_pre[] = {
    "SCOUT DENIM: This is my",
    "patrol route! Nobody",
    "passes without a battle!",
    NULL};
static const char *const dlg_denim_post[] = {
    "The wilds up here are",
    "tough. Train hard, kid!",
    NULL};
static const char *const dlg_bram_pre[] = {
    "HIKER BRAM: These rocks?",
    "I carried them here",
    "myself! Show me strength!",
    NULL};
static const char *const dlg_bram_post[] = {
    "Strong! The pass treats",
    "the strong kindly.",
    NULL};
static const char *const dlg_iris_pre[] = {
    "FOREST KEEPER IRIS:",
    "The creatures of this",
    "pass answer to me.",
    "Prove your bond - battle!",
    NULL};
static const char *const dlg_iris_post[] = {
    "The pass is yours to",
    "walk. Beyond lies",
    "Emberwood... when the",
    "road opens. Keep growing!",
    NULL};

static const TrainerDef trainer_liam = { "CAMPER LIAM", 4, { 3, 5 }, { 4, 4 }, 2, 320, dlg_liam_post, 2 };
static const TrainerDef trainer_maya = { "PICNICKER MAYA", 4, { 6, 4 }, { 5, 5 }, 2, 240, dlg_maya_post, 4 };
static const TrainerDef trainer_denim = { "SCOUT DENIM", 4, { 5, 7 }, { 9, 9 }, 2, 360, dlg_denim_post, 8 };
static const TrainerDef trainer_bram = { "HIKER BRAM", 1, { 4, 6 }, { 10, 9 }, 2, 400, dlg_bram_post, 16 };
static const TrainerDef trainer_iris = { "KEEPER IRIS", 1, { 2, 6, 9 }, { 12, 12, 15 }, 3, 900, dlg_iris_post, 32 };

static const NpcDef npcs_0[] = {
    {5, 4, 0, 2, 1, NULL, NULL, 0},
};

static const NpcDef npcs_1[] = {
    {6, 5, 0, 1, 3, NULL, NULL, 0},
    {3, 6, 3, 4, 0, dlg_assistant, NULL, 0},
};

static const NpcDef npcs_2[] = {
    {2, 2, 0, 3, 2, NULL, NULL, 0},
};

static const NpcDef npcs_3[] = {
    {6, 16, 1, 4, 0, dlg_kid_pond, NULL, 0},
    {8, 20, 2, 1, 0, dlg_villager, NULL, 0},
};

static const NpcDef npcs_4[] = {
    {11, 14, 2, 4, 4, dlg_liam_pre, &trainer_liam, 0},
    {12, 22, 2, 4, 4, dlg_maya_pre, &trainer_maya, 0},
    {10, 3, 0, 1, 5, dlg_hiker, NULL, 6},
};

static const NpcDef npcs_5[] = {
    {2, 2, 0, 1, 6, NULL, NULL, 0},
};

static const NpcDef npcs_6[] = {
    {13, 6, 2, 4, 4, dlg_denim_pre, &trainer_denim, 0},
    {8, 14, 3, 1, 4, dlg_bram_pre, &trainer_bram, 0},
    {13, 2, 2, 1, 4, dlg_iris_pre, &trainer_iris, 0},
};

static const SignDef signs_3[] = {
    {15, 16, "VERDAN TOWN\nWhere journeys sprout."},
};

static const SignDef signs_4[] = {
    {16, 27, "ROUTE 1\nVERDAN TOWN - MT. CINDER"},
};

static const SignDef signs_6[] = {
    {18, 24, "ROUTE 2\nEMBERWOOD PASS"},
    {18, 1, "KEEPER'S POST\nGUARDIAN OF THE PASS"},
};

static const Encounter encs_4[] = {
    {3, 2, 4, 45},
    {5, 2, 4, 25},
    {6, 2, 3, 15},
    {7, 3, 4, 10},
    {4, 3, 5, 5},
};

static const Encounter encs_6[] = {
    {3, 8, 10, 20},
    {5, 9, 11, 15},
    {6, 8, 10, 15},
    {7, 9, 11, 15},
    {4, 10, 12, 15},
    {10, 10, 12, 10},
    {8, 12, 12, 4},
    {9, 12, 12, 3},
    {11, 12, 12, 3},
};

const MapDef MAPS[NUM_MAPS] = {
    { "PLAYER'S HOUSE", 11, 9, rows_players_house, warps_0, 1, npcs_0, 1, NULL, 0, NULL, 0, 0 },
    { "MAPLE'S LAB", 13, 10, rows_maples_lab, warps_1, 1, npcs_1, 2, NULL, 0, NULL, 0, 0 },
    { "CARE STATION", 10, 8, rows_care_station, warps_2, 1, npcs_2, 1, NULL, 0, NULL, 0, 0 },
    { "VERDAN TOWN", 28, 24, rows_verdan_town, warps_3, 6, npcs_3, 2, signs_3, 1, NULL, 0, 0 },
    { "ROUTE 1", 20, 34, rows_route_1, warps_4, 4, npcs_4, 3, signs_4, 1, encs_4, 5, 12 },
    { "VERDAN MART", 10, 8, rows_verdan_mart, warps_5, 1, npcs_5, 1, NULL, 0, NULL, 0, 0 },
    { "ROUTE 2", 20, 26, rows_route_2, warps_6, 2, npcs_6, 3, signs_6, 2, encs_6, 9, 12 },
};
